abstract: There's no fear with this elegant site scraper
author: 'Yung-chung Lin <xern@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: FEAR-API
no_index:
  directory:
    - inc
    - t
recommends:
  Tie::ShareLite: 0
requires:
  Compress::Zlib: 0
  DB_File: 0
  Digest::MD5: 0
  Email::Find: 0
  File::MMagic: 0
  File::Slurp: 0
  File::Temp: 0
  Filter::Simple: 0
  HTML::Encoding: 0
  HTML::Entities: 0
  HTML::LinkExtractor: 0
  HTTP::Proxy: 0
  HTTP::Recorder: 0
  IO::All: 0
  IO::String: 0
  IPC::SysV: 0
  Inline: 0
  Inline::Files: 0
  Parallel::ForkManager: 0
  Regexp::Bind: 0
  Regexp::Common: 0
  Sort::Versions: 0
  Spiffy: 0
  Template: 0
  Template::Extract: 0
  Text::CSV: 0
  Text::Iconv: 0
  WWW::Mechanize: 0
  XML::XPath: 0
  YAML: 0
version: 0.481
